In [1]:
import torch

In [3]:
# Simple Function
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [4]:
# Can also create x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
x.grad  # The gradient is None by default

In [5]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad == 4 * x

tensor([True, True, True, True])

In [8]:
x.grad.zero_()  # Reset the gradient
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [10]:
# Backward for Non-Scalar Variables
x.grad.zero_()
y = x * x
y.backward(gradient=torch.ones(len(y)))  # Faster: y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [12]:
# Detaching Computation
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [13]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x


tensor([True, True, True, True])

In [17]:
# Detaching Computation - if not detach
x.grad.zero_()
y = x * x
u = y
z = u * x

z.sum().backward()
x.grad, u, x.grad == u

(tensor([ 0.,  3., 12., 27.]),
 tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>),
 tensor([ True, False, False, False]))

In [18]:
# Gradients and Python Control Flow
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [19]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [20]:
a.grad == d / a

tensor(True)